import React, { useState } from "react";
import { StyleSheet, Text, View, ScrollView, TextInput, Alert } from "react-native";
import { useRouter } from "expo-router";
import AppHeader from "@/components/common/AppHeader";
import PrimaryButton from "@/components/common/PrimaryButton";
import { COLORS } from "@/constants/colors";
import { generateFarmingPlan } from "@/services/geminiApi";
import * as FileSystem from "expo-file-system";
import * as Sharing from "expo-sharing";

interface FishFormData {
  pondSize: string;
  location: string;
  fishSpecies: string;
  waterSource: string;
  pondType: string;
  budget: string;
  experience: string;
  feedType: string;
  marketAccess: string;
  waterQuality: string;
  pondDepth: string;
  stockingDensity: string;
  currentFish: string;
  equipment: string;
  goals: string;
}

export default function FishPlanning() {
  const router = useRouter();
  const [formData, setFormData] = useState<FishFormData>({
    pondSize: "",
    location: "",
    fishSpecies: "",
    waterSource: "",
    pondType: "",
    budget: "",
    experience: "",
    feedType: "",
    marketAccess: "",
    waterQuality: "",
    pondDepth: "",
    stockingDensity: "",
    currentFish: "",
    equipment: "",
    goals: "",
  });
  const [loading, setLoading] = useState(false);
  const [aiResponse, setAiResponse] = useState<string>("");

  const handleInputChange = (field: keyof FishFormData, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const handleSubmit = async () => {
    // Validate required fields
    const requiredFields = ['pondSize', 'location', 'fishSpecies', 'waterSource', 'budget'];
    const missingFields = requiredFields.filter(field => !formData[field as keyof FishFormData]);
    
    if (missingFields.length > 0) {
      Alert.alert("Missing Information", "Please fill in all required fields marked with *");
      return;
    }

    setLoading(true);
    try {
      const response = await generateFarmingPlan("fish", formData);
      setAiResponse(response);
    } catch (error) {
      console.error("Error generating plan:", error);
      Alert.alert("Error", "Failed to generate fish farming plan. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const downloadPlan = async () => {
    if (!aiResponse) return;

    try {
      const fileName = `fish_plan_${new Date().toISOString().split('T')[0]}.txt`;
      const fileUri = FileSystem.documentDirectory + fileName;
      
      const content = `FISH FARMING PLAN
Generated on: ${new Date().toLocaleDateString()}

FARM DETAILS:
- Pond Size: ${formData.pondSize}
- Location: ${formData.location}
- Fish Species: ${formData.fishSpecies}
- Water Source: ${formData.waterSource}
- Pond Type: ${formData.pondType}
- Budget: ${formData.budget}
- Experience Level: ${formData.experience}
- Feed Type: ${formData.feedType}
- Market Access: ${formData.marketAccess}
- Water Quality: ${formData.waterQuality}
- Pond Depth: ${formData.pondDepth}
- Stocking Density: ${formData.stockingDensity}
- Current Fish: ${formData.currentFish}
- Equipment: ${formData.equipment}
- Goals: ${formData.goals}

AI RECOMMENDATIONS:
${aiResponse}

---
Generated by FarmConnect AI Planning System`;

      await FileSystem.writeAsStringAsync(fileUri, content);
      await Sharing.shareAsync(fileUri);
    } catch (error) {
      console.error("Error downloading plan:", error);
      Alert.alert("Error", "Failed to download plan. Please try again.");
    }
  };

  const sendToGovernment = async () => {
    if (!aiResponse) return;
    
    Alert.alert(
      "Send to Government",
      "This feature will send your fish farming plan to relevant government officers. Would you like to proceed?",
      [
        { text: "Cancel", style: "cancel" },
        { text: "Send", onPress: async () => {
          try {
            Alert.alert("Success", "Your fish farming plan has been prepared for sending to government officers. Please contact your local fisheries development office to submit this plan.");
          } catch (error) {
            console.error("Error sending email:", error);
            Alert.alert("Error", "Failed to send plan. Please try again or contact your local fisheries development office directly.");
          }
        }}
      ]
    );
  };

  const InputField = ({ 
    label, 
    field, 
    placeholder, 
    required = false, 
    multiline = false 
  }: { 
    label: string; 
    field: keyof FishFormData; 
    placeholder: string; 
    required?: boolean; 
    multiline?: boolean; 
  }) => (
    <View style={styles.inputContainer}>
      <Text style={styles.label}>
        {label} {required && <Text style={styles.required}>*</Text>}
      </Text>
      <TextInput
        style={[styles.input, multiline && styles.multilineInput]}
        placeholder={placeholder}
        value={formData[field]}
        onChangeText={(value) => handleInputChange(field, value)}
        multiline={multiline}
        numberOfLines={multiline ? 3 : 1}
      />
    </View>
  );

  return (
    <View style={styles.container}>
      <AppHeader 
        title="Fish Planning" 
        showBackButton={true}
      />
      
      <ScrollView 
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
      >
        <Text style={styles.title}>Fish Farming Plan</Text>
        <Text style={styles.subtitle}>
          Fill out the details below to get personalized fish farming recommendations
        </Text>

        <InputField 
          label="Pond Size" 
          field="pondSize" 
          placeholder="e.g., 1 acre, 0.5 hectares, 100x50 feet" 
          required 
        />
        
        <InputField 
          label="Location" 
          field="location" 
          placeholder="e.g., Dhaka, Bangladesh" 
          required 
        />
        
        <InputField 
          label="Fish Species" 
          field="fishSpecies" 
          placeholder="e.g., Rohu, Catla, Tilapia, Pangasius" 
          required 
        />
        
        <InputField 
          label="Water Source" 
          field="waterSource" 
          placeholder="e.g., Tube well, River, Rainwater, Municipal" 
          required 
        />
        
        <InputField 
          label="Budget" 
          field="budget" 
          placeholder="e.g., 50,000 BDT, Low budget, High investment" 
          required 
        />
        
        <InputField 
          label="Pond Type" 
          field="pondType" 
          placeholder="e.g., Earthen pond, Concrete tank, Plastic lined" 
        />
        
        <InputField 
          label="Experience Level" 
          field="experience" 
          placeholder="e.g., Beginner, Intermediate, Expert" 
        />
        
        <InputField 
          label="Feed Type" 
          field="feedType" 
          placeholder="e.g., Commercial pellets, Natural feed, Mixed feeding" 
        />
        
        <InputField 
          label="Market Access" 
          field="marketAccess" 
          placeholder="e.g., Local market, Wholesale, Direct selling" 
        />
        
        <InputField 
          label="Water Quality" 
          field="waterQuality" 
          placeholder="e.g., Good, Moderate, Needs treatment" 
        />
        
        <InputField 
          label="Pond Depth" 
          field="pondDepth" 
          placeholder="e.g., 6 feet, 2 meters, Variable depth" 
        />
        
        <InputField 
          label="Stocking Density" 
          field="stockingDensity" 
          placeholder="e.g., 5000 fish/acre, High density, Low density" 
        />
        
        <InputField 
          label="Current Fish Stock" 
          field="currentFish" 
          placeholder="e.g., 1000 fingerlings, Empty pond, Mixed species" 
        />
        
        <InputField 
          label="Available Equipment" 
          field="equipment" 
          placeholder="e.g., Aerator, Water pump, Nets, Basic tools" 
        />
        
        <InputField 
          label="Goals & Objectives" 
          field="goals" 
          placeholder="e.g., Maximum profit, Sustainable farming, Export quality" 
          multiline 
        />

        <PrimaryButton
          title={loading ? "Generating Plan..." : "Generate AI Plan"}
          onPress={handleSubmit}
          disabled={loading}
          style={styles.submitButton}
        />

        {aiResponse && (
          <View style={styles.responseContainer}>
            <Text style={styles.responseTitle}>AI Recommendations</Text>
            <Text style={styles.responseText}>{aiResponse}</Text>
            
            <View style={styles.actionButtons}>
              <PrimaryButton
                title="Download Plan"
                onPress={downloadPlan}
                style={styles.actionButton}
              />
              <PrimaryButton
                title="Send to Government"
                onPress={sendToGovernment}
                style={styles.secondaryButton}
              />
            </View>
          </View>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    marginBottom: 8,
    color: COLORS.textPrimary,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 16,
    color: COLORS.textSecondary,
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 22,
  },
  inputContainer: {
    marginBottom: 16,
  },
  label: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: 8,
  },
  required: {
    color: COLORS.error,
  },
  input: {
    backgroundColor: COLORS.inputBackground,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: COLORS.textPrimary,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  multilineInput: {
    height: 80,
    textAlignVertical: "top",
  },
  submitButton: {
    marginTop: 24,
    marginBottom: 16,
  },
  responseContainer: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  responseTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: 12,
  },
  responseText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    lineHeight: 20,
    marginBottom: 16,
  },
  actionButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  actionButton: {
    flex: 1,
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: COLORS.secondary,
  },
});
